services:
    frontend:
        build: ./frontend # it moves to frontend folder and looks for Dockerfile
        image: rakeshakuluru/frontend:1.0.0 # it is equivalent to docker build -t rakeshakuluru/frontend:1.0.0
        container_name: frontend
        depends_on:
            - catalogue
            - user
            - cart
            - shipping
        ports:
            - "80:80"
    catalogue:
        build: ./catalogue # it moves to catalogue folder and looks for Dockerfile
        image: rakeshakuluru/catalogue:1.0.0 # it is equivalent to docker build -t rakeshakuluru/catalogue:1.0.0
        container_name: catalogue
        depends_on:
            - mongodb
    user:
        build: ./user # it moves to user folder and looks for Dockerfile
        image: rakeshakuluru/user:1.0.0 # it is equivalent to docker build -t rakeshakuluru/user:1.0.0
        container_name: user
        depends_on:
            - redis
            - mongodb
    cart:
        build: ./cart # it moves to cart folder and looks for Dockerfile
        image: rakeshakuluru/cart:1.0.0 # it is equivalent to docker build -t rakeshakuluru/cart:1.0.0
        container_name: cart
        depends_on:
            - redis
            - catalogue
    shipping:
        build: ./shipping # it moves to shipping folder and looks for Dockerfile
        image: rakeshakuluru/shipping:1.0.0 # it is equivalent to docker build -t rakeshakuluru/shipping:1.0.0
        container_name: shipping
        depends_on:
            - mysql
            - cart
    payment:
        build: ./payment # it moves to payment folder and looks for Dockerfile
        image: rakeshakuluru/payment:1.0.0 # it is equivalent to docker build -t rakeshakuluru/payment:1.0.0
        container_name: payment
        depends_on:
            - rabbitmq
            - cart
            - user
    mongodb:
        build: ./mongodb # it moves to mongodb folder and looks for Dockerfile
        image: rakeshakuluru/mongodb:1.0.0 # it is equivalent to docker build -t rakeshakuluru/mongodb:1.0.0
        container_name: mongodb
        volumes:
          - mongodb:/data/db # it is equivalent to docker volume create mongodb and docker run -v mongodb:/data/db
    mysql:
        build: ./mysql # it moves to mysql folder and looks for Dockerfile
        image: rakeshakuluru/mysql:1.0.0 # it is equivalent to docker build -t rakeshakuluru/mysql:1.0.0
        container_name: mysql
        volumes:
          - mysql:/var/lib/mysql # it is equivalent to docker volume create mysql and docker run -v mysql:/var/lib/mysql
    redis:
        image: redis:7.0 # using pre-built redis image
        container_name: redis
        volumes:
          - redis:/data # it is equivalent to docker volume create redis and docker run -v redis:/data
    rabbitmq:
        image: rabbitmq:3 #we are calling rabbitmq image from docker hub directly so we don't have to build it
        environment:
            RABBITMQ_DEFAULT_USER: roboshop
            RABBITMQ_DEFAULT_PASS: roboshop123
        container_name: rabbitmq
        volumes:
          - rabbitmq:/var/lib/rabbitmq # it is equivalent to docker volume create rabbitmq and docker run -v rabbitmq:/var/lib/rabbitmq

networks:
    default:
        name: roboshop
        driver: bridge
        external: false

volumes:
    mongodb:
    mysql:
    redis:
    rabbitmq: