services:
  mongodb:
    build: ./mongodb
    image: rakeshakuluru/mongodb:1.1.1
    container_name: mongodb
    volumes:
      - mongodb:/data/db
  
  redis:
    build: ./redis
    image: rakeshakuluru/redis:1.1.1
    container_name: redis
    volumes:
      - redis:/data

  rabbitmq:
    build: ./rabbitmq
    image: rakeshakuluru/rabbitmq:1.1.1
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=roboshop123
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    
  mysql:
    build: ./mysql
    image: rakeshakuluru/mysql:1.1.1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql

#Now setup the backend services
  catalogue:
    build: ./catalogue
    image: rakeshakuluru/catalogue:1.1.1
    container_name: catalogue
    depends_on:
      - mongodb
    environment:
      - MONGO=true
      - MONGO_URL=mongodb://mongodb:27017/catalogue
  
  user:
    build: ./user
    image: rakeshakuluru/user:1.1.1
    container_name: user
    depends_on:
      - redis
      - mongodb
  cart:
    build: ./cart
    image: rakeshakuluru/cart:1.1.1
    container_name: cart
    depends_on:
      - redis
      - catalogue
  
  shipping:
    build: ./shipping
    image: rakeshakuluru/shipping:1.1.1
    container_name: shipping
    depends_on:
      - cart
      - mysql
  
  payment:
    build: ./payment
    image: rakeshakuluru/payment:1.1.1
    container_name: payment
    depends_on:
      - cart
      - user
      - rabbitmq
  
  dispatch:
    build: ./dispatch
    image: rakeshakuluru/dispatch:1.1.1
    container_name: dispatch
    depends_on:
      - rabbitmq

#Now configure the frontend service
  frontend:
    build: ./frontend
    image: rakeshakuluru/frontend:1.1.1
    container_name: frontend
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
    ports:
      - 80:80

# Now configure the networks
networks:
  default: 
    driver: bridge
    name: roboshop
    external: false

# Now configure volumes
volumes:
  mongodb:
  mysql:
  redis:
  rabbitmq:
